site_name: 'RegExp DSL'
site_url: 'https://juan-medina.github.io/regexp-dsl/'
site_description: 'Expressive regular expressions with a domain specific language.'
site_author: 'Juan Medina'
copyright: '© 2020 Juan Medina'

repo_url: https://github.com/juan-medina/regexp-dsl
repo_name: 'GitHub'

pages:
  - Home: 'index.md'
  - Examples : 'examples.md'
  - API Documentation: 'api/regexp-dsl/com.medina.juan.regexp.dsl/index.md'
theme:
  name: material
  palette:
    primary: 'cyan'
    accent: 'deep-purple'
docs_dir: src/docs
site_dir: docs
markdown_extensions:
  - codehilite
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      check_paths: true
  - tables
  - admonition